### PR TITLE
CISTDHF and CCSD

### PR DESCRIPTION
**Pull request by pwborthwick**
Hi @jjgoings ,
    I've converted print statements to Python 3 format in main routine and routines upto and including ccsd.py. I've tested cistdhf and (corrected) ccsd using geometry and integrals matching Crawford projects for water in sto-3g and these agree fine. I'm trying to check the eom-ccsd using 3 references and it's frustrating that there are disagreements in the equations for the intermediates between them. Do you have a definitive reference (like the one you have referenced equations from in your code) that you could let me have, it would help a lot when you have time.
   I've checked H<sub>SS</sub>block of eom-ccsd and that looks fine, but H</sub>SD</sub> has sign issues (but you've said Gwaltney has errors and it's my only source of Hbar partitioning). If I can get the eom-ccsd sorted then the eom-mbpt should follow more easily.  I'm concerned not to take up your time with this so if you feel this is being too much trouble let me know.
           Peter

### CODE REVIEW

**Comment by pwborthwick** [comment]
This is eomccsd.py. All print statements converted to Python 3 format.

**Equation #38**

                    HDS[iajb,kc] += (i==k)*ts[a,m]*ts[e,i]*ints[m,b,c,e] - \
                                    (i==k)*ts[b,m]*ts[e,i]*ints[m,a,c,e] - \
                                    (j==k)*ts[a,m]*ts[e,j]*ints[m,b,c,e] + \
                                    (j==k)*ts[b,m]*ts[e,j]*ints[m,a,c,e] #38 

These lines should contain index elements only once in rhs equation. Code for #38 has two 'i's and two 'j's in lines 139-142. changed (i==k) <-> (j==k).

**Equation #57**

                      HDD[iajb,kcld] += (a==c)*(i==l)*(b==d)*fs[k,e]*ts[e,j] - \
                                        (a==c)*(j==l)*(b==d)*fs[k,e]*ts[e,i] # 57

The H<sub>DD</sub> block is defined as F<sub>bc</sub> **-** F<sub>kj</sub> + .... 
with F<sub>kj</sub>= +*f*<sub>kj</sub> + f<sub>ke</sub> t<sub>ej</sub>+ ...
as sign of F<sub>kj</sub> in H<sub>DD</sub> is negative then these terms are also negative
**-** f<sub>kj</sub> **-** f<sub>ke</sub> t<sub>ej</sub> 
The first term is equation #53 

                    HDD[iajb,kcld] += (j==l)*(a==d)*(b==c)*fs[k,i] - \
                                      (i==l)*(a==d)*(b==c)*fs[k,j] # 53
and has correct sign. Second term is equation #57 and has wrong sign.

**Equation #63**

                      HDD[iajb,kcld] += (i==k)*(j==l)*(b==d)*ints[m,a,e,c]*ts[e,m] - \
                                          (i==k)*(j==l)*(a==d)*ints[m,b,e,c]*ts[e,m]  # 63 
  
The H<sub>DD</sub> block is defined as F<sub>bc</sub> **-** F<sub>kj</sub> +  .... 
with  F<sub>bc</sub> =*f*<sub>bc</sub> **-** f<sub>mc</sub> t<sub>bm</sub> **+** t<sub>em</sub> <bm||ce> + ...
The  term **+** t<sub>em</sub> <bm||ce> can be re-written as   **+** t<sub>em</sub> <mb||ec> 
This is opposite to sign in code.

**Equations #71 and #76**

                          HDD[iajb,kcld] += 0.5*(i==k)*(j==l)*(a==d)*ints[m,n,e,c]*td[b,e,n,m] - \
                                            0.5*(i==k)*(j==l)*(b==d)*ints[m,n,e,c]*td[a,e,n,m] # 71
                          HDD[iajb,kcld] += (i==k)*(j==l)*(a==d)*ints[m,n,e,c]*ts[e,m]*ts[b,n] - \
                                            (i==k)*(j==l)*(b==d)*ints[m,n,e,c]*ts[e,m]*ts[a,n]# 76

The H<sub>DD</sub> block is defined as F<sub>bc</sub> **-** F<sub>kj</sub> +  .... 
with F<sub>bc</sub> = ... **-** 0.5&tau;<sub>ebmn</sub> <mn||ec>. 
This can be re-written as **-** 0.5t<sub>benm</sub><mn||ec> - t<sub>bn</sub>t<sub>em</sub><mn||ec>.
The first equation is #71 but sign is wrong in code. 
Second term is equation #76 should also be negative but positive in code.

**Equation #69 and #75**

                          HDD[iajb,kcld] += 0.5*(a==c)*(i==l)*(b==d)*ints[m,k,e,f]*td[f,e,j,m] - \
                                            0.5*(a==c)*(j==l)*(b==d)*ints[m,k,e,f]*td[f,e,i,m] # 69

H<sub>DD</sub> block is defined as  F<sub>bc</sub> **-** F<sub>kj</sub> +  .... 
with F<sub>kj</sub> = ... **+** 0.5&tau;<sub>efjm</sub><km||ef>. 
This can be re-written as **+** 0.5t<sub>fejm</sub> <mk||ef> **+** t<sub>fj</sub>t<sub>em</sub> <mk||ef> 
[as interchange of indexes *ef* on &tau;, and indexes *km* on eri => overall sign the same]
As F<sub>kj</sub> is itself negative both terms are also negative. 
#69 has wrong sign in code.
 The second term t<sub>fj</sub>t<sub>em</sub> <mk||ef> is equation #75

                          HDD[iajb,kcld] += (a==c)*(i==l)*(b==d)*ints[m,k,e,f]*ts[f,j]*ts[e,m] - \
                                            (a==c)*(j==l)*(b==d)*ints[m,k,e,f]*ts[f,i]*ts[e,m]# 75

 and again the sign is wrong in the code.

**Equation #20**
For H<sub>SD</sub> block references give F<sub>me</sub> + 0.5W<sub>amef</sub> - 0.5W<sub>mnie</sub>, 
re-indexing (m->l, e->d, f->c) gives F<sub>ld</sub> + 0.5W<sub>aldc</sub> - 0.5W<sub>lkid</sub>
with F<sub>ld</sub>  = *f*<sub>ld</sub> + t<sub>em</sub><km||ce> 
re-writing as *f*<sub>ld</sub><mk||ec> gives #16 and #21 as coded

                HSD[ia,kcld] += (i==k)*(a==c)*fs[l,d] # 16
                    HSD[ia,kcld] += ints[m,k,e,c]*ts[e,m]*(i==l)*(a==d) # 21

the +0.5W<sub>aldc</sub> term = +0.5<al||dc> - 0.5 t<sub>am</sub><ml||dc> 
= -0.5<al||cd>  + 0.5 t<sub>am</sub><ml||cd> these are equations #17 and #20 with opposite signs to code.

               HSD[ia,kcld] += 0.5*ints[a,l,c,d]*(i==k) # 17
                  HSD[ia,kcld] += -0.5*ints[m,l,c,d]*ts[a,m]*(i==k) # 20
 
finally  - 0.5W<sub>lkid</sub> = -0.5<lk||id> - 0.5t<sub>ie</sub><lk||ed> 
= 0.5<kl||id>  + 0.5t<sub>ie</sub><kl||ed> these are equations #18 and #19 with opposite sign to code.

                  HSD[ia,kcld] += -0.5*ints[k,l,e,d]*ts[e,i]*(a==c) # 19
                HSD[ia,kcld] += -0.5*ints[k,l,i,d]*(a==c) # 18


I've corrected the code according to what I think is correct, but it's only what *I* think is right working from what references I have. I'm particularly worried by the H<sub>SD</sub> block as the signs I get here are at odds with equation A11 in your paper. 
           Peter

**Comment by pwborthwick** [comment]
Hi @jjgoings,
   For when you're less busy.

    I've rechecked the equations and cannot make my sign differences go away. I've summarised what I've done below. I get the same results for most of the equations it's just a few that are holding me up in moving on to eom-mbpt.

+ I've checked the Gwaltney partitioning equations with code in *pyscf* and they are in agreement.
+  I can't see any differences between your equations in 'EOM-diagrams-pt3' and the implementation in code.
+  I've checked the sign on perturbation diagrams and can't see any problems there. 
+ The Hirata equations that I've checked seem consistent with your equations.
+ Your equations, diagrams and Hirata appear to form a consistent set.
+ Equations derived from *pyscf* and published intermediate values  have some differences in sign that I cannot account for. This is particularly true for the H<sub>SD</sub> block. I've checked several times now and cannot reconcile the equations.
+ I have perturbative triples code for *pyqchem* if you want me to add it?
+ When I cut and pasted code from *pyqchem* into an editor Python gave 'inconstent use of tabs and spaces' message. Try mp2.py for example, it looks OK in Github. I can correct this if you like.
+ If we can reconcile the signs on the equations I am happy with eom-ccsd. My working follows, perhaps you can see why I get a different sign for some equations?...
- - -
 I've been checking Gwaltney partitioning equations against pyscf as currently Gwaltney is the only source for them. pyscf has for H<sub>SS</sub> and H<sub>SD</sub>
 
    Hr1  = lib.einsum('ae,ie->ia', imds.Fvv, r1)
    Hr1 -= lib.einsum('mi,ma->ia', imds.Foo, r1)
    Hr1 += lib.einsum('me,imae->ia', imds.Fov, r2)
    Hr1 += lib.einsum('maei,me->ia', imds.Wovvo, r1)
    Hr1 -= 0.5*lib.einsum('mnie,mnae->ia', imds.Wooov, r2)
    Hr1 += 0.5*lib.einsum('amef,imef->ia', imds.Wvovv, r2)

This implies 
[F<sub>ae</sub> - F<sub>mi</sub> + W<sub>maei</sub> ] + [F<sub>me</sub> - 0.5 W<sub>mnie</sub> + 0.5 W<sub>amef</sub>]
These agree with Gwaltney.

For H<sub>DS</sub> and H<sub>DD</sub>

    tmpab = lib.einsum('be,ijae->ijab', imds.Fvv, r2)
    tmpab -= 0.5*lib.einsum('mnef,ijae,mnbf->ijab', imds.Woovv, imds.t2, r2)
    tmpab -= lib.einsum('mbij,ma->ijab', imds.Wovoo, r1)
    tmpab -= lib.einsum('amef,ijfb,me->ijab', imds.Wvovv, imds.t2, r1)
    tmpij  = lib.einsum('mj,imab->ijab', -imds.Foo, r2)
    tmpij -= 0.5*lib.einsum('mnef,imab,jnef->ijab', imds.Woovv, imds.t2, r2)
    tmpij += lib.einsum('abej,ie->ijab', imds.Wvvvo, r1)
    tmpij += lib.einsum('mnie,njab,me->ijab', imds.Wooov, imds.t2, r1)

    tmpabij = lib.einsum('mbej,imae->ijab', imds.Wovvo, r2)
    tmpabij = tmpabij - tmpabij.transpose(1,0,2,3)
    tmpabij = tmpabij - tmpabij.transpose(0,1,3,2)
    Hr2 = tmpabij

    Hr2 += tmpab - tmpab.transpose(0,1,3,2)
    Hr2 += tmpij - tmpij.transpose(1,0,2,3)
    Hr2 += 0.5*lib.einsum('mnij,mnab->ijab', imds.Woooo, r2)
    Hr2 += 0.5*lib.einsum('abef,ijef->ijab', imds.Wvvvv, r2)

tmpab = P(ab) {F<sub>be</sub> - 0.5 W<sub>mnef</sub>t<sup>ae</sup><sub>ij</sub> - W<sub>mbij</sub> - W<sub>amef</sub>t<sup>fb</sup><sub>ij</sub>}
tmpij    = P(ij) {- F<sub>mj</sub> - 0.5 W<sub>mnef</sub>t<sup>ab</sup><sub>im</sub> + W<sub>abej</sub> + W<sub>mnie</sub>t<sup>ab</sup><sub>nj</sub>}
tmpabij = P(ij)P(ab) W<sub>mbej</sub>
Last 2 Hr2 terms are 0.5 W<sub>mnij</sub> and 0.5 W<sub>abef</sub>

writing this as [P(ab) - W<sub>mbij</sub> + P(ij) W<sub>abej</sub>  - P(ab) W<sub>amef</sub>t<sup>fb</sup><sub>ij</sub> + P(ij) W<sub>mnie</sub>t<sup>ab</sup><sub>nj</sub>] + [P(ab) F<sub>be</sub> -  P(ij)  F<sub>mj</sub>  + 0.5 W<sub>abef</sub> +  0.5 W<sub>mnij</sub> +  P(ij)P(ab) W<sub>mbej</sub> - P(ab)  0.5 W<sub>mnef</sub>t<sup>ae</sup><sub>ij</sub> - P(ij)  0.5 W<sub>mnef</sub>t<sup>ab</sup><sub>im</sub> ]

 [P(ab) - W<sub>mbij</sub> + P(ij) W<sub>abej</sub>  - P(ab) W<sub>amef</sub>t<sup>fb</sup><sub>ij</sub> + P(ij) W<sub>mnie</sub>t<sup>ab</sup><sub>nj</sub>]  can be re-written as (as b<->a or i<->j changes sign eg)
+ **+ P(ab)  W<sub>maij</sub>** 
+ **+ P(ij) W<sub>abej</sub>**
+ P(ab) W<sub>bmef</sub>t<sup>fa</sup><sub>ij</sub>  -> - P(ab) W<sub>bmfe</sub>t<sup>fa</sup><sub>ij</sub> -> **+  P(ab) W<sub>bmfe</sub>t<sup>af</sup><sub>ij</sub>**
+ -P(ij) W<sub>mnje</sub>t<sup>ab</sup><sub>ni</sub> -> + P(ij) W<sub>nmje</sub>t<sup>ab</sup><sub>ni</sub> -> **- P(ij) W<sub>nmje</sub>t<sup>ab</sup><sub>in</sub>**
These agree with Gwaltney for H<sub>DS</sub>
image

 [P(ab) F<sub>be</sub> -  P(ij)  F<sub>mj</sub>  + 0.5 W<sub>abef</sub> +  0.5 W<sub>mnij</sub> +  P(ij)P(ab) W<sub>mbej</sub> - P(ab)  0.5 W<sub>mnef</sub>t<sup>ae</sup><sub>ij</sub> - P(ij)  0.5 W<sub>mnef</sub>t<sup>ab</sup><sub>im</sub> ] can be re-written as
+ **P(ab) F<sub>be</sub>**
+ **-  P(ij)  F<sub>mj</sub>**
+ **+ 0.5 W<sub>abef</sub>**
+ **+ 0.5 W<sub>mnij</sub>**
+ +P(ij)P(ab) W<sub>mbej</sub> -> **P(ij)P(ab) W<sub>bmje</sub>**
+ -P(ab)  0.5 W<sub>mnef</sub>t<sup>ae</sup><sub>ij</sub> -> + P(ab)  0.5 W<sub>mnfe</sub>t<sup>af</sup><sub>ij</sub> -> -P(ab)  0.5 W<sub>nmfe</sub>t<sup>af</sup><sub>ij</sub> -> +P(ab)  0.5 W<sub>nmfe</sub>t<sup>bf</sup><sub>ij</sub> -> **-P(ab)  0.5 W<sub>nmfe</sub>t<sup>fb</sup><sub>ij</sub>**
+ +P(ij)  0.5 W<sub>nmef</sub>t<sup>ab</sup><sub>in</sub> -> - P(ij)  0.5 W<sub>nmfe</sub>t<sup>ab</sup><sub>in</sub> -> **+P(ij)  0.5 W<sub>nmfe</sub>t<sup>ab</sup><sub>jn</sub>**
This agrees with Gwaltney too.
image
Happy that partition equations are correct.
- - -
Seeing what pyscf says about H<sub>SD</sub> where we have a difference of signs.
image
Looking at the second term  +0.5 W<sub>amef</sub> in *psi4numpy*

    def build_Hvovv(self):
        """ <am|Hbar|ef> = <am||ef> - t_na <nm||ef> """
        self.Hvovv = self.get_MO('vovv').copy()
        self.Hvovv -= ndot('na,nmef->amef', self.t1, self.get_MO('oovv'))
        return self.Hvovv

this is + <am||ef> - t<sup>a</sup><sub>n</sub> <nm||ef> 
Our indexes mean m->l and e->d, which in turn makes double-bar term <*v*l||d*v*> (vovv) or - <*v*l||*v*d>, which is different  sign to #17.
Illinois reference has eg

    [ + 1.0 ] * Sum ( h3 p4 ) * f ( h3 p4 ) * x ( p4 p2 h3 h1 )
    [ + 0.5 ] * Sum ( h3 h4 p5 ) * v ( h3 h4 h1 p5 ) * x ( p5 p2 h3 h4 )
    [ + 0.5 ] * Sum ( h3 p4 p5 ) * v ( h3 p2 p4 p5 ) * x ( p4 p5 h3 h1 )
    [ + 0.5 ] * Sum ( h4 h5 p3 p6 ) * t ( p3 h1 ) * v ( h4 h5 p3 p6 ) * x ( p6 p2 h4 h5 )
    [ + 0.5 ] * Sum ( h3 h4 p5 p6 ) * t ( p2 h3 ) * v ( h3 h4 p5 p6 ) * x ( p5 p6 h4 h1 )
    [ + 1.0 ] * Sum ( h4 h5 p3 p6 ) * t ( p3 h4 ) * v ( h4 h5 p3 p6 ) * x ( p6 p2 h5 h1 )

These are
+ *f*<sub>kd</sub> x<sub>dbki</sub> this has to be (k->l, i->k, b->c) **f<sub>ld</sub>** x<sub>dclk</sub> #16
+ 0.5<kl||ie> x<sub>ebkl</sub> -> (e->d, b->c, k->l, l->k) gives +0.5<lk||id> x<sub>dclk</sub> or **-0.5<kl||id>** x<sub>dclk</sub> #18
+ 0.5<kb||de> x<sub>deki</sub> -> (e->c, k->l, i->k,b->a) gives =0.5<la||dc> x<sub>dclk</sub> or **+0.5<al||cd>** x<sub>dclk</sub> #17
+ 0.5t<sub>ci</sub> <lm||cf> x<sub>fblm</sub> -> (f->d, b->c,m->k,c->e) gives +0.5t<sub>ei</sub><lk||ed> or **-0.5t<sub>ei</sub> <kl||ed>**  x<sub>dclk</sub> #19
+ 0.5t<sub>bk</sub> <kl||ef> x<sub>efli</sub> -> (e->d, f->c, i->k, b->a, k->m) gives +0.5t<sub>am</sub> <ml||dc> or **-0.5t<sub>am</sub> <ml||cd>** x<sub>dclk</sub> #20
+ +t<sub>cl</sub> <lm||cf> x<sub>fbmi</sub> -> (c->e, l->m, f->c, b->d, m->k, i->l) gives **+t<sub>em</sub> <mk||ec>** x<sub>cdkl</sub> #21

These agree with your equations.
- - -
pyscf definition of F<sub>ae</sub> is

    def cc_Fvv(t1, t2, eris):
        nocc, nvir = t1.shape
        fov = eris.fock[:nocc,nocc:]
        fvv = eris.fock[nocc:,nocc:]
        eris_vovv = np.asarray(eris.ovvv).transpose(1,0,3,2)
        tau_tilde = make_tau(t2, t1, t1,fac=0.5)
       Fae = fvv - 0.5*einsum('me,ma->ae',fov, t1)
       Fae += einsum('mf,amef->ae', t1, eris_vovv)
       Fae -= 0.5*einsum('mnaf,mnef->ae', tau_tilde, eris.oovv)
       return Fae

This means F<sub>ae</sub> = *f*<sub>ae</sub> - 0.5 t<sup>a</sup><sub>m</sub> *f*<sub>me</sub> + t<sup>f</sup><sub>m</sub><am||ef> - 0.5&tau;<sup>af</sup><sub>mn</sub><mn||ef> 
Translating indices a->b, e->c, 
F<sub>bc</sub> = *f*<sub>bc</sub> - 0.5 t<sup>b</sup><sub>m</sub> *f*<sub>mc</sub> +  t<sup>e</sup><sub>m</sub><bm||ce> - 0.5&tau;<sup>be</sup><sub>mn</sub><mn||ce> 
+  *f*<sub>bc</sub>  is your equation #52
+ -0.5 t<sup>b</sup><sub>m</sub> *f*<sub>mc</sub>   #58
+ +t<sup>e</sup><sub>m</sub><bm||ce> -> + t<sup>e</sup><sub>m</sub><mb||ec>  **-** #63 
+ -0.5&tau;<sup>be</sup><sub>mn</sub><mn||ce> -> +0.5&tau;<sup>be</sup><sub>mn</sub><mn||ec> -> -0.5&tau;<sup>be</sup><sub>nm</sub><mn||ec> **-** #71 and **-** #76
Still get different signs to you.

**Comment by pwborthwick** [comment]
@jjgoings,
   I'm at a standstill now. I have papers which don't agree on the ee-eom equations eg
Gwaltney
image
Gauss & Stanton
image
(it's not the 0.5,  that's OK it's the sign t.f term)
Then Gwaltney and Stanton & Bartlett have
image
while Gauss & Stanton have
image

I decided to implement the psi4numpy eom-ccsd code. I did a copy and paste all the files into a single file and ran it (once I'd removed '#'s from print statements which the psi4 interpreter thought were EOL characters?!). It worked fine for the cc-pvdz  test example, then fails comparison tests with Psi4 for everything else (convergence OK). The psi4numpy ccsd agrees with the corrected code for pyqchem ccsd btw. 
It's strange that psi4numpy should agree with Psi4 on cc-pvdz and fail for everything else I've tried eg sto-3g, 3-21g, 6-31g, dz etc. For H<sub>2</sub>O in sto-3g the psi4numpty 1st 3 roots are 0,0,0 (program says 'Davidson converged!) against +0.32324,+0.39485,+0.49686 for Psi4. Although you can see values of   0.32324, 0.39485 and 0.49687 in the 11th iteration of psi4numpy before iterations 12 and 13 zero out all the root values so maybe a Davidson problem. 

I assume that Psi4 is correct (and consistent with Gaussian, nwchem etc). Running psi4numpy for H<sub>2</sub>  gives roots of 0,0,0 again with Psi4 giving 15.898419860623038 and  25.361595698515725 eV. The good news is your unmodified code gives a first singlet at 15.89840677559601 eV (which is close) but the next singlet is at 30.52161397477038 eV which is not close. (I'm guessing Psi4 is returning singlet states because I find it's documentation unhelpful). My 'corrections' make matters worse - why I get the sign differences I don't know (I've checked and they won't go away). 
  Well I think that's all I have to offer. I'm sure 'the truth is out there' but at the moment I have no idea how to find it. I'm going to move on to other things because I've been staring at these equations for too long now, but let me know if you re-visit this in the future.
      Peter

**Review by jjgoings — APPROVED** [review]
@pwborthwick  I think all of these look OK. My goal is to write some unit tests soon to streamline the debugging a bit. Sorry I've been a bit slammed and haven't been able to give this the thought I would like. Hopefully soon!

**Pull request merged**
